Fix: Sitemap content type error
The error `src/pages/SitemapGenerator.tsx(91,16): error TS2540: Cannot assign to 'contentType' because it is a read-only property.` was caused by attempting to directly assign to `document.contentType`. This commit replaces the content of the document by using `document.replaceChildren()` instead.